spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vegetfood
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhtuanle939@gmail.com
    password: rvmpkhpvqhuqnsnd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 403029958635-p7dinpb27kg1a5tfpip2u1053n3r8i0a.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1205549046785011
            client-secret: f7c9c2a4b73f460f3f2236310074d7fc
  main:
    allow-bean-definition-overriding: true

server:
  error:
    whitelabel:
      enabled: false
    path: /error
